[phases.build]
cmds = [
  "npm ci --include=dev",
  "./node_modules/.bin/tsc --project tsconfig.json",
  "cp src/database/schema.sql dist/database/schema.sql"
]

[phases.deploy]
cmds = ["npm prune --production"]

[start]
cmd = "node dist/server.js"
